import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { AuthProvider } from "@/context/authContext";
import { CartProvider } from "@/context/cartContext";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'
import { ReactNode } from "react";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Read Realm",
  description: "Generated by Rafiul Alam Bhuiyan",
};

export default function RootLayout({
  children,
}:  Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          
          <CartProvider>
            <Navbar />
            <ToastContainer/>
            {children}
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
